version: "3.8"
services:

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "publisher"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./createDb.sql:/docker-entrypoint-initdb.d/createDb.sql
    networks:
      - postgres-network
    ports:
      - "5440:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-publisher}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-publisher}
    ports:
      - "${PGADMIN_PORT:-8081}:80"
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on: 
      - db
    networks:
      - postgres-network
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
